config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  match 'login' => 'user_sessions#new', :as => :login, :via => :get
  match 'logout' => 'user_sessions#destroy', :as => :logout, :via => :get

  resources :users
  resources :user_sessions
  resources :password_resets

  namespace :admin do
    resources :courses
  end
  resources :courses do
    member do
      post 'make_mentorship'
      delete 'destroy_mentorship'
    end
  end
  resources :course_buckets do
    member do
      post 'make_bucketship'
      delete 'destroy_bucketship'
    end
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  end

  def create
    user = login(params[:email], params[:password], params[:remember_me])
    if user
      redirect_back_or_to root_url, :notice => "Eingeloggt!"
    else
      flash.now.alert = "Email or password was invalid"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, {:role => 'form', :method => :post} do %>
  <div class="form-group">
    <label for="email">Email</label>
    <%= email_field_tag :email, params[:email], {class:'form-control', id: 'email'} %>
  </div>
  <div class="form-group">
    <label for="password">Passwort</label>
    <%= password_field_tag :password, nil, {class:'form-control', id: 'password'} %>
  </div>
  <div class="checkbox">
    <label>
      <%= check_box_tag :remember%>Angemeldet bleiben
    </label>
  </div>
  <%= submit_tag "Anmelden", {class: 'btn btn-default'} %>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>
<%= render 'form' %>
<%= link_to 'Passwort vergessen?', new_password_reset_path %>
 | <%= link_to 'Home', root_path %>