config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  match 'login' => 'user_sessions#new', :as => :login, :via => :get
  match 'logout' => 'user_sessions#destroy', :as => :logout, :via => :get

  resources :users
  resources :user_sessions
  resources :password_resets

  namespace :admin do
    resources :courses
  end
  resources :courses do
    member do
      post 'make_mentorship'
      delete 'destroy_mentorship'
    end
  end
  resources :course_buckets do
    member do
      post 'make_bucketship'
      delete 'destroy_bucketship'
    end
  end

end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < Admin::AdminController
  def index
    @active_courses = Course.where(active: true)
    @inactive_courses = Course.where(active: false)
    render :index
  end

  def show
    @course = Course.find_by_id(params[:id])
    if @course
      @mentors = @course.mentors.map(&:user)
      @students = @course.students.map(&:user)
      render :show
    else
      redirect_to admin_courses_path, alert: "Kurs nicht vorhanden."
    end
  end

  def edit
    @course = Course.find_by_id(params[:id])
    if @course
      render :edit
    else
      redirect_to admin_courses_path, alert: "Kurs nicht vorhanden."
    end
  end

  def update
    @course = Course.find_by_id(params[:id])
    if @course
      @course.title = params[:course][:title] if params[:course][:title]
      @course.active = params[:course][:active] unless params[:course][:active].nil?
      if @course.save
        respond_to do |format|
          format.html { redirect_to admin_courses_path, notice: "Kurs erfolgreich updated!" }
          format.js {}
        end
      else
        flash.now[:error] = @course.errors.full_messages.join(" ")
        render :edit
      end
    else
      redirect_to admin_courses_path, alert: "Kurs nicht vorhanden."
    end
  end

  def new
    @course = Course.new
    render :new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to admin_courses_path, :notice => "Neuer Kurs erfolgreich angelegt."
    else
      flash.now[:error] = @course.errors.full_messages.join(" ")
      render :new
    end
  end
  private

  def course_params
    params.require(:course).permit(:title, :active)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_filter :require_login
  def index
    @user_courses = current_user.mentor.courses
    @other_courses = Course.all - @user_courses
    render :index
  end

  def make_mentorship
    @course = Course.find_by_id(params[:id])
    if @course
      current_user.mentor.courses << @course
      respond_to do |format|
        format.html { redirect_to courses_path, notice: "Mentorship erfolgreich etabliert." }
        format.js {}
      end
    else
      redirect_to courses_path, alert: "Kurs nicht vorhanden!"
    end
  end

  def destroy_mentorship
    @course = current_user.mentor.courses.find_by_id(params[:id])
    if @course
      current_user.mentor.courses.delete(@course)
      respond_to do |format|
        format.html { redirect_to courses_path, notice: "Mentorship erfolgreich gelöscht." }
        format.js {}
      end
    else
      redirect_to courses_path, alert: "Kurs nicht vorhanden!"
    end
  end
end

app/views/admin/courses/_course.html.erb
<div id=<%= course.id %> class="row">
  <div class="col-xs-12 col-md-8"><%= link_to course.title, admin_course_path(course) %></div>
  <div class="col-xs-6 col-md-4 btn-group">
    <%= link_to icon("edit", 2), edit_admin_course_path(course), class: "btn" %>
    <%= form_for [:admin, course], method: :put, remote: true, html: { class: "ajax_form" } do |f| %>
      <%= f.hidden_field :active, value: (!course.active).to_s %>
      <button type="submit" class="btn btn-primary btn-xs">
        <%= icon(icon_type, 2) %>
        <%= button %>
      </button>
    <% end %>
  </div>
</div>

app/views/admin/courses/_form.html.erb
<%= form_for [:admin, @course], {:role => 'form'} do |f| %>
  <div class="form-group">
    <label for="title">Titel</label>
    <%= f.text_field :title, {class:'form-control', id: 'title'} %>
  </div>
  <div class="checkbox">
    <label>
      <%= f.check_box :active%> aktuell
    </label>
  </div>
  <%= submit_tag "Senden", {class: 'btn btn-default'} %>
<% end %>

app/views/admin/courses/edit.html.erb
<h1>Kurs editieren</h1>
<%= render partial: "form", object: @course %>

app/views/admin/courses/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= icon(:list, 2) %>
    Aktuelle Kurse
  </div>
  <div id="active" class="panel-body">
    <% @active_courses.each do |course| %>
      <%= render partial: "course", locals: { course: course, button: "Deaktivieren", icon_type: "minus-square" } %>
    <% end %>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <%= icon(:list, 2) %>
    Andere Kurse
  </div>
  <div id="inactive" class="panel-body">
    <% @inactive_courses.each do |course| %>
      <%= render partial: "course", locals: { course: course, button: "Aktivieren", icon_type: "plus-square" } %>
    <% end %>
  </div>
</div>

app/views/admin/courses/new.html.erb
<h1>Neuen Kurs anlegen</h1>
<%= render partial: "form", object: @course %>

app/views/admin/courses/show.html.erb
<h1><%= link_to @course.title, edit_admin_course_path(@course) %></h1>
<div class="col-xs-9 col-md-6">
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= icon("users", 2) %>
      Mentoren
    </div>
    <% if @mentors.count > 0 %>
      <ul class="list-group">
        <% @mentors.each do |mentor| %>
          <li class="list-group-item">
            <h4 class="list-group-item-heading">
              <%= mentor.name %>
            </h4>
            <%= mentor.email %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <div class="panel-body">
        Für diesen Kurs hat sich momentan noch kein Mentor gemeldet.
      </div>
    <% end %>
  </div>
</div>
<div class="col-xs-9 col-md-6">
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= icon("users", 2) %>
      Studenten
    </div>
    <% if @students.count > 0 %>
      <ul class="list-group">
        <% @students.each do |student| %>
          <li class="list-group-item">
            <h4 class="list-group-item-heading">
              <%= student.name %>
            </h4>
            <%= student.email %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <div class="panel-body">
        Für diesen Kurs hat sich momentan noch kein Student gemeldet.
      </div>
    <% end %>
  </div>
</div>

app/views/admin/courses/update.js.erb
$("#<%= @course.id %>").remove();
<% if @course.active %>
  $("#active").append("<%= escape_javascript(render(partial: @course, locals: {course: @course, button: 'Deaktivieren', icon_type: 'minus-square'})) %>");
<% else %>
  $("#inactive").append("<%= escape_javascript(render(partial: @course, locals: {course: @course, button: 'Aktivieren', icon_type: 'plus-square'})) %>");
<% end %>