config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  match 'login' => 'user_sessions#new', :as => :login, :via => :get
  match 'logout' => 'user_sessions#destroy', :as => :logout, :via => :get

  resources :users
  resources :user_sessions
  resources :password_resets

  namespace :admin do
    resources :courses
  end
  resources :courses do
    member do
      post 'make_mentorship'
      delete 'destroy_mentorship'
    end
  end
  resources :course_buckets do
    member do
      post 'make_bucketship'
      delete 'destroy_bucketship'
    end
  end

end

app/views/layouts/_navbar.html.erb
<%= nav_bar :static => :top, :brand => "One2One", :responsive => true, :inverse => true, :role => "navigation" do %>
  <%= menu_group do %>
    <%= menu_item "Home", root_path %>
    <%= menu_item "Kontakt", root_path %>
    <% if logged_in? %>
      <%= menu_item "Mentor", courses_path %>
      <%= drop_down "Student" do %>
        <% current_user.student.course_buckets.each do |bucket| %>
          <%= menu_item stringify_semester(bucket.semester), course_bucket_path(bucket.id) %>
        <% end %>
      <% end %>
      <% if current_user.admin? %>
        <%= drop_down "Admin" do %>
          <%= menu_item "Kurseverwaltung", admin_courses_path %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
  <%= menu_group :pull => :right do %>
    <% if logged_in? %>
      <%= menu_item "#{current_user.email} abmelden", logout_path %>
    <% else %>
      <%= menu_item "Registrieren", new_user_path %>
      <%= menu_item "Anmelden", login_path  %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OneToOne</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/navbar" %>
  <div class='container-fluid'>
    <%= flash_message(flash) %>
    <%= yield %>
  </div>
</body>
</html>